# Generated by Django 3.2.12 on 2022-11-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frafer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='UserModel',
        ),
    ]
