# Generated by Django 3.2.12 on 2022-11-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frafer', '0002_rename_userform_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='RegistrationModel',
        ),
    ]
